services:
  # GENERAL
  pagination.query_pagination:
    class: Everlution\PaginationBundle\Pagination\QueryPagination
    arguments:
      - '@pagination.filter.null'
      - '@pagination.sort.null'
      - '%everlution.pagination.max_page_size%'

  pagination.filter.null:
    class: Everlution\PaginationBundle\Pagination\Filter\NullFilterQuery

  pagination.sort.null:
    class: Everlution\PaginationBundle\Pagination\Sort\NullSortQuery

  # TRANSFORMER
  pagination.transformer.page_to_limit_offset:
    class: Everlution\PaginationBundle\Pagination\Transformer\PageToLimitOffset
    public: false

  pagination.transformer.page_to_limit_offset_query_transformer:
    class: Everlution\PaginationBundle\Pagination\Transformer\PageToLimitOffsetQueryTransformer
    arguments:
      - '@pagination.transformer.page_to_limit_offset'
      - '%everlution.pagination.default_page_size%'

  # EVENT LISTENER
  pagination.event.listener.page_to_limit_offset_transformer:
    class: Everlution\PaginationBundle\Event\Listener\PageToLimitOffsetTransformer
    arguments:
      - '@pagination.transformer.page_to_limit_offset_query_transformer'
    tags:
      - { name: kernel.event_listener, event: kernel.request }

  # TWIG EXTENSION
  pagination.twig.extension.paginate:
    class: Everlution\PaginationBundle\Twig\PaginateExtension
    arguments:
      - '@twig'
    tags:
      - { name: twig.extension }

  pagination.twig.extension.sortable_header:
    class: Everlution\PaginationBundle\Twig\SortableHeaderExtension
    arguments:
      - '@twig'
      - '@pagination.sort.direction_helper'
      - '@pagination.sort.icon.font_awsome'
      - '%everlution.pagination.sortable_header_template%'
    tags:
      - { name: twig.extension }

  # SORTABLE HEADER
  pagination.sort.direction_helper:
    class: Everlution\PaginationBundle\Sort\Properties\DirectionHelper
    arguments:
      - '@request_stack'

  pagination.sort.icon.font_awsome:
    class: Everlution\PaginationBundle\Sort\Properties\Icon\FontAwesome

  pagination.sort.column.doctrine_factory:
    class: Everlution\PaginationBundle\Pagination\Sort\Column\DoctrineColumnFactory

  pagination.sort.request_sort_query:
    class: Everlution\PaginationBundle\Sort\RequestSortQuery
    arguments:
      - '@request_stack'
      - '@pagination.sort.column.doctrine_factory'
      - '%everlution.pagination.default_sort_query_string%'
